### ISSUE TITLE
the links in the project were invalid

### ISSUE THREAD

**Issue by Xiaflowers** [thodan/epos#1]
Hello, first of all, thank you for your sharing. I found that all the links in the project were invalid. Could you please tell me how to get it now?
Also, I found that Osmesa and Progression-X were not compiled successfully. Will this affect my training?
I've now got my own dataset in BOP format.

Looking forward to your reply！
thank you!

**Comment by thodan** [comment]
Hello, which links do not work? (I've clicked on a few and all worked. Try to copy the URL to the address bar.)

Progression-X is not required for training, but Osmesa is so you should get that compiled.

**Comment by Xiaflowers** [comment]
Thank you for your reply.I copy the URL to the address bar and it works.
However, Osmeda was still not compiled successfully, resulting in the following error during training:
AttributeError: module 'external.bop_renderer' has no attribute 'Renderer'.

So I really want to be a guide to how do we solve this problem.
Looking forward to your reply！
thank you!

**Comment by thodan** [comment]
It seems you modified the python code and added `external` in `external.bop_renderer` (when importing `bop_renderer`)? Did you follow the instructions in section "Setup"? In particular, did you add `export PYTHONPATH=$REPO_PATH/external/bop_renderer/build:$PYTHONPATH` to file `$CONDA_PREFIX/etc/conda/activate.d/env_vars.sh`?

**Comment by Xiaflowers** [comment]
Thank you for your advice! These days I have recompiled the code according to "setup", upgraded GCC to 9.3, and configured OSMESA using source code compilation. Now the code is running successfully! However, the problem of insufficient GPU memory will appear soon after the beginning of the training, so I would like to ask what is the minimum computer configuration required for this project? Or how do I adjust the batch so that the training runs properly?

**Comment by thodan** [comment]
I was training each model on a single GPU (Tesla P100) with 16GB of memory. You can reduce the memory requirements by, e.g., reducing the number of surface fragments or using a lighter weight backbone network.

**Comment by monajalal** [comment]
> Thank you for your reply.I copy the URL to the address bar and it works. However, Osmeda was still not compiled successfully, resulting in the following error during training: AttributeError: module 'external.bop_renderer' has no attribute 'Renderer'.
> 
> So I really want to be a guide to how do we solve this problem. Looking forward to your reply！ thank you!

I have the same error:

`AttributeError: module 'bop_renderer' has no attribute 'Renderer'`
