### ISSUE TITLE
about the checkpoint

### ISSUE THREAD

**Issue by Xiaflowers** [thodan/epos#3]
can you tell me how to get the resnet backbone pre-trained models, I only found the model for xception-65.

Looking forward to your reply！

**Comment by thodan** [comment]
Hi, only Xception-65 models are available (I didn't train any other backbone with the released version of code).

**Comment by Xiaflowers** [comment]
I'm sorry to bother you so often, I am a green hand in this field and know very little.
I downloaded the checkpoint file from the TensorFlow website to initialize the ResNet and MobileNet models, but both had problems.
So I would really like to know how you got Xception's pre-training model.

Thank you very much for your reply！
Wish you all the best！

**Comment by thodan** [comment]
I downloaded the pre-trained model from:
https://github.com/tensorflow/models/blob/master/research/deeplab/g3doc/model_zoo.md

I don't think I did anything special with the model, but you may compare the init mode I used (http://ptak.felk.cvut.cz/6DB/public/epos_store/imagenet-coco-xc65.zip) with the model downloaded form the website above.

**Comment by Xiaflowers** [comment]
Oh! Thank you very much! I found it.
