### ISSUE TITLE
wrong link

### ISSUE THREAD

**Issue by peppa114** [thodan/epos#4]
Hi, thodan. Firstly, thanks for your sharing. However, when I compiled the OSMesa, I found the link "ftp://ftp.freedesktop.org/pub/mesa/older-versions/17.x/mesa-${mesaversion}.tar.gz" did't work. The file I downloaded always unzipped unsuccessfully. I guess the downloaded file is defective because it just 324 bytes. Could you share a new link or the file?
![2021-08-13 18-10-13屏幕截图](https://user-images.githubusercontent.com/83171253/129341739-26e23a4e-5bea-4909-87a4-aa818b620285.png)

**Comment by thodan** [comment]
You are right the link does not work for some reason now. I would propose to consult https://github.com/devernay/osmesa-install (from where the installation script originates) or maybe wait some time (maybe the server is down).

**Comment by peppa114** [comment]
Thanks for your reply! I have successfully downloaded using 'https' link, and it worked.
