### ISSUE TITLE
Depth information in training

### ISSUE THREAD

**Issue by iroCl** [thodan/epos#5]
Are depth images really necessary for training? I am quite confused because in your paper you say you only use RGB images, but when I try to train my own dataset, it requires depth images (when running calc_gt_info).

**Comment by VinGerk** [comment]
Hi! I am new in these stuff and had the same question regarding the depth images. What are they actually required for in training and testing? Was there any help about it?

**Comment by thodan** [comment]
Hello. The depth images are not used when training EPOS. All BOP datasets provide depth images though and some of the scripts in this repo require these images (mostly for historical reasons). The scripts should be easy to modify such as this requirement is removed.
