### ISSUE TITLE
How to label ground truth of b(u)

### ISSUE THREAD

**Issue by pyni** [thodan/epos#6]
Hi~
Thanks for your wonderful work.
After reading you paper, I have a question that can be hardly found in your paper.
Your paper says,'if the ground-truth one-hot distribution ¯bi(u) indicates a different fragment at pixels with similar appearance, the network is expected to learn at such pixels the same probability bij (u) for all the indicated fragments.'

 Your paper says 'Vectors a¯(u),¯bi(u), and r¯ij (u) are obtained by rendering the 3D object models in the ground-truth poses with a custom OpenGL shader.' But I can not find how to get the ground-truth of ¯bi(u) especially for partial symmetries.  Could you please give me some suggestions?

**Comment by thodan** [comment]
Hi pyni. Only the (single) ground-truth object pose is used during training, no ground-truth about symmetries is used. ¯bi(u) is calculated using the ground-truth object pose and the 3D object model -- the code can be found here: https://github.com/thodan/epos/blob/master/epos_lib/datagen_utils.py#L143
